export interface Surah {
  id: number;
  number: number;
  name: string;
  englishName: string;
  englishNameTranslation: string;
  numberOfAyahs: number;
  revelationType: string;
  arabicNumber: string;
  juzNumber?: number;
  revelationOrder?: number;
}

// Arabic numerals for 1-114
const arabicNumbers = [
  '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩', '١٠',
  '١١', '١٢', '١٣', '١٤', '١٥', '١٦', '١٧', '١٨', '١٩', '٢٠',
  '٢١', '٢٢', '٢٣', '٢٤', '٢٥', '٢٦', '٢٧', '٢٨', '٢٩', '٣٠',
  '٣١', '٣٢', '٣٣', '٣٤', '٣٥', '٣٦', '٣٧', '٣٨', '٣٩', '٤٠',
  '٤١', '٤٢', '٤٣', '٤٤', '٤٥', '٤٦', '٤٧', '٤٨', '٤٩', '٥٠',
  '٥١', '٥٢', '٥٣', '٥٤', '٥٥', '٥٦', '٥٧', '٥٨', '٥٩', '٦٠',
  '٦١', '٦٢', '٦٣', '٦٤', '٦٥', '٦٦', '٦٧', '٦٨', '٦٩', '٧٠',
  '٧١', '٧٢', '٧٣', '٧٤', '٧٥', '٧٦', '٧٧', '٧٨', '٧٩', '٨٠',
  '٨١', '٨٢', '٨٣', '٨٤', '٨٥', '٨٦', '٨٧', '٨٨', '٨٩', '٩٠',
  '٩١', '٩٢', '٩٣', '٩٤', '٩٥', '٩٦', '٩٧', '٩٨', '٩٩', '١٠٠',
  '١٠١', '١٠٢', '١٠٣', '١٠٤', '١٠٥', '١٠٦', '١٠٧', '١٠٨', '١٠٩', '١١٠',
  '١١١', '١١٢', '١١٣', '١١٤'
];

export const surahs: Surah[] = [
  {
    id: 1,
    number: 1,
    name: "الفاتحة",
    englishName: "Al-Fatihah",
    englishNameTranslation: "The Opener",
    numberOfAyahs: 7,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[0],
    juzNumber: 1,
    revelationOrder: 5
  },
  {
    id: 2,
    number: 2,
    name: "البقرة",
    englishName: "Al-Baqarah",
    englishNameTranslation: "The Cow",
    numberOfAyahs: 286,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[1],
    juzNumber: 1,
    revelationOrder: 87
  },
  {
    id: 3,
    number: 3,
    name: "آل عمران",
    englishName: "Ali 'Imran",
    englishNameTranslation: "Family of Imran",
    numberOfAyahs: 200,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[2],
    juzNumber: 3,
    revelationOrder: 89
  },
  {
    id: 4,
    number: 4,
    name: "النساء",
    englishName: "An-Nisa",
    englishNameTranslation: "The Women",
    numberOfAyahs: 176,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[3],
    juzNumber: 4,
    revelationOrder: 92
  },
  {
    id: 5,
    number: 5,
    name: "المائدة",
    englishName: "Al-Ma'idah",
    englishNameTranslation: "The Table Spread",
    numberOfAyahs: 120,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[4],
    juzNumber: 6,
    revelationOrder: 112
  },
  {
    id: 6,
    number: 6,
    name: "الأنعام",
    englishName: "Al-An'am",
    englishNameTranslation: "The Cattle",
    numberOfAyahs: 165,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[5],
    juzNumber: 7,
    revelationOrder: 55
  },
  {
    id: 7,
    number: 7,
    name: "الأعراف",
    englishName: "Al-A'raf",
    englishNameTranslation: "The Heights",
    numberOfAyahs: 206,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[6],
    juzNumber: 8,
    revelationOrder: 39
  },
  {
    id: 8,
    number: 8,
    name: "الأنفال",
    englishName: "Al-Anfal",
    englishNameTranslation: "The Spoils of War",
    numberOfAyahs: 75,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[7],
    juzNumber: 9,
    revelationOrder: 88
  },
  {
    id: 9,
    number: 9,
    name: "التوبة",
    englishName: "At-Tawbah",
    englishNameTranslation: "The Repentance",
    numberOfAyahs: 129,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[8],
    juzNumber: 10,
    revelationOrder: 113
  },
  {
    id: 10,
    number: 10,
    name: "يونس",
    englishName: "Yunus",
    englishNameTranslation: "Jonah",
    numberOfAyahs: 109,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[9],
    juzNumber: 11,
    revelationOrder: 51
  },
  {
    id: 11,
    number: 11,
    name: "هود",
    englishName: "Hud",
    englishNameTranslation: "Hud",
    numberOfAyahs: 123,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[10],
    juzNumber: 11,
    revelationOrder: 52
  },
  {
    id: 12,
    number: 12,
    name: "يوسف",
    englishName: "Yusuf",
    englishNameTranslation: "Joseph",
    numberOfAyahs: 111,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[11],
    juzNumber: 12,
    revelationOrder: 53
  },
  {
    id: 13,
    number: 13,
    name: "الرعد",
    englishName: "Ar-Ra'd",
    englishNameTranslation: "The Thunder",
    numberOfAyahs: 43,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[12],
    juzNumber: 13,
    revelationOrder: 96
  },
  {
    id: 14,
    number: 14,
    name: "إبراهيم",
    englishName: "Ibrahim",
    englishNameTranslation: "Abraham",
    numberOfAyahs: 52,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[13],
    juzNumber: 13,
    revelationOrder: 72
  },
  {
    id: 15,
    number: 15,
    name: "الحجر",
    englishName: "Al-Hijr",
    englishNameTranslation: "The Rocky Tract",
    numberOfAyahs: 99,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[14],
    juzNumber: 14,
    revelationOrder: 54
  },
  {
    id: 16,
    number: 16,
    name: "النحل",
    englishName: "An-Nahl",
    englishNameTranslation: "The Bee",
    numberOfAyahs: 128,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[15],
    juzNumber: 14,
    revelationOrder: 70
  },
  {
    id: 17,
    number: 17,
    name: "الإسراء",
    englishName: "Al-Isra",
    englishNameTranslation: "The Night Journey",
    numberOfAyahs: 111,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[16],
    juzNumber: 15,
    revelationOrder: 50
  },
  {
    id: 18,
    number: 18,
    name: "الكهف",
    englishName: "Al-Kahf",
    englishNameTranslation: "The Cave",
    numberOfAyahs: 110,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[17],
    juzNumber: 15,
    revelationOrder: 69
  },
  {
    id: 19,
    number: 19,
    name: "مريم",
    englishName: "Maryam",
    englishNameTranslation: "Mary",
    numberOfAyahs: 98,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[18],
    juzNumber: 16,
    revelationOrder: 44
  },
  {
    id: 20,
    number: 20,
    name: "طه",
    englishName: "Taha",
    englishNameTranslation: "Ta-Ha",
    numberOfAyahs: 135,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[19],
    juzNumber: 16,
    revelationOrder: 45
  },
  {
    id: 21,
    number: 21,
    name: "الأنبياء",
    englishName: "Al-Anbya",
    englishNameTranslation: "The Prophets",
    numberOfAyahs: 112,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[20],
    juzNumber: 17,
    revelationOrder: 73
  },
  {
    id: 22,
    number: 22,
    name: "الحج",
    englishName: "Al-Hajj",
    englishNameTranslation: "The Pilgrimage",
    numberOfAyahs: 78,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[21],
    juzNumber: 17,
    revelationOrder: 103
  },
  {
    id: 23,
    number: 23,
    name: "المؤمنون",
    englishName: "Al-Mu'minun",
    englishNameTranslation: "The Believers",
    numberOfAyahs: 118,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[22],
    juzNumber: 18,
    revelationOrder: 74
  },
  {
    id: 24,
    number: 24,
    name: "النور",
    englishName: "An-Nur",
    englishNameTranslation: "The Light",
    numberOfAyahs: 64,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[23],
    juzNumber: 18,
    revelationOrder: 102
  },
  {
    id: 25,
    number: 25,
    name: "الفرقان",
    englishName: "Al-Furqan",
    englishNameTranslation: "The Criterion",
    numberOfAyahs: 77,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[24],
    juzNumber: 18,
    revelationOrder: 42
  },
  {
    id: 26,
    number: 26,
    name: "الشعراء",
    englishName: "Ash-Shu'ara",
    englishNameTranslation: "The Poets",
    numberOfAyahs: 227,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[25],
    juzNumber: 19,
    revelationOrder: 47
  },
  {
    id: 27,
    number: 27,
    name: "النمل",
    englishName: "An-Naml",
    englishNameTranslation: "The Ant",
    numberOfAyahs: 93,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[26],
    juzNumber: 19,
    revelationOrder: 48
  },
  {
    id: 28,
    number: 28,
    name: "القصص",
    englishName: "Al-Qasas",
    englishNameTranslation: "The Stories",
    numberOfAyahs: 88,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[27],
    juzNumber: 20,
    revelationOrder: 49
  },
  {
    id: 29,
    number: 29,
    name: "العنكبوت",
    englishName: "Al-Ankabut",
    englishNameTranslation: "The Spider",
    numberOfAyahs: 69,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[28],
    juzNumber: 20,
    revelationOrder: 85
  },
  {
    id: 30,
    number: 30,
    name: "الروم",
    englishName: "Ar-Rum",
    englishNameTranslation: "The Romans",
    numberOfAyahs: 60,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[29],
    juzNumber: 21,
    revelationOrder: 84
  },
  {
    id: 31,
    number: 31,
    name: "لقمان",
    englishName: "Luqman",
    englishNameTranslation: "Luqman",
    numberOfAyahs: 34,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[30],
    juzNumber: 21,
    revelationOrder: 57
  },
  {
    id: 32,
    number: 32,
    name: "السجدة",
    englishName: "As-Sajda",
    englishNameTranslation: "The Prostration",
    numberOfAyahs: 30,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[31],
    juzNumber: 21,
    revelationOrder: 75
  },
  {
    id: 33,
    number: 33,
    name: "الأحزاب",
    englishName: "Al-Ahzab",
    englishNameTranslation: "The Combined Forces",
    numberOfAyahs: 73,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[32],
    juzNumber: 21,
    revelationOrder: 90
  },
  {
    id: 34,
    number: 34,
    name: "سبإ",
    englishName: "Saba",
    englishNameTranslation: "Sheba",
    numberOfAyahs: 54,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[33],
    juzNumber: 22,
    revelationOrder: 58
  },
  {
    id: 35,
    number: 35,
    name: "فاطر",
    englishName: "Fatir",
    englishNameTranslation: "Originator",
    numberOfAyahs: 45,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[34],
    juzNumber: 22,
    revelationOrder: 43
  },
  {
    id: 36,
    number: 36,
    name: "يس",
    englishName: "Ya-Sin",
    englishNameTranslation: "Ya Sin",
    numberOfAyahs: 83,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[35],
    juzNumber: 22,
    revelationOrder: 41
  },
  {
    id: 37,
    number: 37,
    name: "الصافات",
    englishName: "As-Saffat",
    englishNameTranslation: "Those who set the Ranks",
    numberOfAyahs: 182,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[36],
    juzNumber: 23,
    revelationOrder: 56
  },
  {
    id: 38,
    number: 38,
    name: "ص",
    englishName: "Sad",
    englishNameTranslation: "The Letter Sad",
    numberOfAyahs: 88,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[37],
    juzNumber: 23,
    revelationOrder: 38
  },
  {
    id: 39,
    number: 39,
    name: "الزمر",
    englishName: "Az-Zumar",
    englishNameTranslation: "The Troops",
    numberOfAyahs: 75,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[38],
    juzNumber: 23,
    revelationOrder: 59
  },
  {
    id: 40,
    number: 40,
    name: "غافر",
    englishName: "Ghafir",
    englishNameTranslation: "The Forgiver",
    numberOfAyahs: 85,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[39],
    juzNumber: 24,
    revelationOrder: 60
  },
  {
    id: 41,
    number: 41,
    name: "فصلت",
    englishName: "Fussilat",
    englishNameTranslation: "Explained in Detail",
    numberOfAyahs: 54,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[40],
    juzNumber: 24,
    revelationOrder: 61
  },
  {
    id: 42,
    number: 42,
    name: "الشورى",
    englishName: "Ash-Shura",
    englishNameTranslation: "The Consultation",
    numberOfAyahs: 53,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[41],
    juzNumber: 25,
    revelationOrder: 62
  },
  {
    id: 43,
    number: 43,
    name: "الزخرف",
    englishName: "Az-Zukhruf",
    englishNameTranslation: "The Ornaments of Gold",
    numberOfAyahs: 89,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[42],
    juzNumber: 25,
    revelationOrder: 63
  },
  {
    id: 44,
    number: 44,
    name: "الدخان",
    englishName: "Ad-Dukhan",
    englishNameTranslation: "The Smoke",
    numberOfAyahs: 59,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[43],
    juzNumber: 25,
    revelationOrder: 64
  },
  {
    id: 45,
    number: 45,
    name: "الجاثية",
    englishName: "Al-Jathiya",
    englishNameTranslation: "The Crouching",
    numberOfAyahs: 37,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[44],
    juzNumber: 25,
    revelationOrder: 65
  },
  {
    id: 46,
    number: 46,
    name: "الأحقاف",
    englishName: "Al-Ahqaf",
    englishNameTranslation: "The Wind-Curved Sandhills",
    numberOfAyahs: 35,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[45],
    juzNumber: 26,
    revelationOrder: 66
  },
  {
    id: 47,
    number: 47,
    name: "محمد",
    englishName: "Muhammad",
    englishNameTranslation: "Muhammad",
    numberOfAyahs: 38,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[46],
    juzNumber: 26,
    revelationOrder: 95
  },
  {
    id: 48,
    number: 48,
    name: "الفتح",
    englishName: "Al-Fath",
    englishNameTranslation: "The Victory",
    numberOfAyahs: 29,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[47],
    juzNumber: 26,
    revelationOrder: 111
  },
  {
    id: 49,
    number: 49,
    name: "الحجرات",
    englishName: "Al-Hujurat",
    englishNameTranslation: "The Rooms",
    numberOfAyahs: 18,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[48],
    juzNumber: 26,
    revelationOrder: 106
  },
  {
    id: 50,
    number: 50,
    name: "ق",
    englishName: "Qaf",
    englishNameTranslation: "The Letter Qaf",
    numberOfAyahs: 45,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[49],
    juzNumber: 26,
    revelationOrder: 34
  },
  {
    id: 51,
    number: 51,
    name: "الذاريات",
    englishName: "Adh-Dhariyat",
    englishNameTranslation: "The Winnowing Winds",
    numberOfAyahs: 60,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[50],
    juzNumber: 26,
    revelationOrder: 67
  },
  {
    id: 52,
    number: 52,
    name: "الطور",
    englishName: "At-Tur",
    englishNameTranslation: "The Mount",
    numberOfAyahs: 49,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[51],
    juzNumber: 27,
    revelationOrder: 76
  },
  {
    id: 53,
    number: 53,
    name: "النجم",
    englishName: "An-Najm",
    englishNameTranslation: "The Star",
    numberOfAyahs: 62,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[52],
    juzNumber: 27,
    revelationOrder: 23
  },
  {
    id: 54,
    number: 54,
    name: "القمر",
    englishName: "Al-Qamar",
    englishNameTranslation: "The Moon",
    numberOfAyahs: 55,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[53],
    juzNumber: 27,
    revelationOrder: 37
  },
  {
    id: 55,
    number: 55,
    name: "الرحمن",
    englishName: "Ar-Rahman",
    englishNameTranslation: "The Beneficent",
    numberOfAyahs: 78,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[54],
    juzNumber: 27,
    revelationOrder: 97
  },
  {
    id: 56,
    number: 56,
    name: "الواقعة",
    englishName: "Al-Waqi'a",
    englishNameTranslation: "The Inevitable",
    numberOfAyahs: 96,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[55],
    juzNumber: 27,
    revelationOrder: 46
  },
  {
    id: 57,
    number: 57,
    name: "الحديد",
    englishName: "Al-Hadid",
    englishNameTranslation: "The Iron",
    numberOfAyahs: 29,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[56],
    juzNumber: 27,
    revelationOrder: 94
  },
  {
    id: 58,
    number: 58,
    name: "المجادلة",
    englishName: "Al-Mujadila",
    englishNameTranslation: "The Pleading Woman",
    numberOfAyahs: 22,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[57],
    juzNumber: 28,
    revelationOrder: 105
  },
  {
    id: 59,
    number: 59,
    name: "الحشر",
    englishName: "Al-Hashr",
    englishNameTranslation: "The Exile",
    numberOfAyahs: 24,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[58],
    juzNumber: 28,
    revelationOrder: 101
  },
  {
    id: 60,
    number: 60,
    name: "الممتحنة",
    englishName: "Al-Mumtahana",
    englishNameTranslation: "She That is to be Examined",
    numberOfAyahs: 13,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[59],
    juzNumber: 28,
    revelationOrder: 91
  },
  {
    id: 61,
    number: 61,
    name: "الصف",
    englishName: "As-Saf",
    englishNameTranslation: "The Ranks",
    numberOfAyahs: 14,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[60],
    juzNumber: 28,
    revelationOrder: 109
  },
  {
    id: 62,
    number: 62,
    name: "الجمعة",
    englishName: "Al-Jumu'a",
    englishNameTranslation: "The Congregation",
    numberOfAyahs: 11,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[61],
    juzNumber: 28,
    revelationOrder: 110
  },
  {
    id: 63,
    number: 63,
    name: "المنافقون",
    englishName: "Al-Munafiqun",
    englishNameTranslation: "The Hypocrites",
    numberOfAyahs: 11,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[62],
    juzNumber: 28,
    revelationOrder: 104
  },
  {
    id: 64,
    number: 64,
    name: "التغابن",
    englishName: "At-Taghabun",
    englishNameTranslation: "The Mutual Disillusion",
    numberOfAyahs: 18,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[63],
    juzNumber: 28,
    revelationOrder: 108
  },
  {
    id: 65,
    number: 65,
    name: "الطلاق",
    englishName: "At-Talaq",
    englishNameTranslation: "The Divorce",
    numberOfAyahs: 12,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[64],
    juzNumber: 28,
    revelationOrder: 99
  },
  {
    id: 66,
    number: 66,
    name: "التحريم",
    englishName: "At-Tahrim",
    englishNameTranslation: "The Prohibition",
    numberOfAyahs: 12,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[65],
    juzNumber: 28,
    revelationOrder: 107
  },
  {
    id: 67,
    number: 67,
    name: "الملك",
    englishName: "Al-Mulk",
    englishNameTranslation: "The Sovereignty",
    numberOfAyahs: 30,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[66],
    juzNumber: 29,
    revelationOrder: 77
  },
  {
    id: 68,
    number: 68,
    name: "القلم",
    englishName: "Al-Qalam",
    englishNameTranslation: "The Pen",
    numberOfAyahs: 52,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[67],
    juzNumber: 29,
    revelationOrder: 2
  },
  {
    id: 69,
    number: 69,
    name: "الحاقة",
    englishName: "Al-Haaqqa",
    englishNameTranslation: "The Reality",
    numberOfAyahs: 52,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[68],
    juzNumber: 29,
    revelationOrder: 78
  },
  {
    id: 70,
    number: 70,
    name: "المعارج",
    englishName: "Al-Ma'arij",
    englishNameTranslation: "The Ascending Stairways",
    numberOfAyahs: 44,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[69],
    juzNumber: 29,
    revelationOrder: 79
  },
  {
    id: 71,
    number: 71,
    name: "نوح",
    englishName: "Nuh",
    englishNameTranslation: "Noah",
    numberOfAyahs: 28,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[70],
    juzNumber: 29,
    revelationOrder: 71
  },
  {
    id: 72,
    number: 72,
    name: "الجن",
    englishName: "Al-Jinn",
    englishNameTranslation: "The Jinn",
    numberOfAyahs: 28,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[71],
    juzNumber: 29,
    revelationOrder: 40
  },
  {
    id: 73,
    number: 73,
    name: "المزمل",
    englishName: "Al-Muzzammil",
    englishNameTranslation: "The Enshrouded One",
    numberOfAyahs: 20,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[72],
    juzNumber: 29,
    revelationOrder: 3
  },
  {
    id: 74,
    number: 74,
    name: "المدثر",
    englishName: "Al-Muddathir",
    englishNameTranslation: "The Cloaked One",
    numberOfAyahs: 56,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[73],
    juzNumber: 29,
    revelationOrder: 4
  },
  {
    id: 75,
    number: 75,
    name: "القيامة",
    englishName: "Al-Qiyama",
    englishNameTranslation: "The Resurrection",
    numberOfAyahs: 40,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[74],
    juzNumber: 29,
    revelationOrder: 31
  },
  {
    id: 76,
    number: 76,
    name: "الانسان",
    englishName: "Al-Insan",
    englishNameTranslation: "The Man",
    numberOfAyahs: 31,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[75],
    juzNumber: 29,
    revelationOrder: 98
  },
  {
    id: 77,
    number: 77,
    name: "المرسلات",
    englishName: "Al-Mursalat",
    englishNameTranslation: "The Emissaries",
    numberOfAyahs: 50,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[76],
    juzNumber: 29,
    revelationOrder: 33
  },
  {
    id: 78,
    number: 78,
    name: "النبإ",
    englishName: "An-Naba",
    englishNameTranslation: "The Tidings",
    numberOfAyahs: 40,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[77],
    juzNumber: 30,
    revelationOrder: 80
  },
  {
    id: 79,
    number: 79,
    name: "النازعات",
    englishName: "An-Nazi'at",
    englishNameTranslation: "Those Who Drag Forth",
    numberOfAyahs: 46,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[78],
    juzNumber: 30,
    revelationOrder: 81
  },
  {
    id: 80,
    number: 80,
    name: "عبس",
    englishName: "Abasa",
    englishNameTranslation: "He Frowned",
    numberOfAyahs: 42,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[79],
    juzNumber: 30,
    revelationOrder: 24
  },
  {
    id: 81,
    number: 81,
    name: "التكوير",
    englishName: "At-Takwir",
    englishNameTranslation: "The Overthrowing",
    numberOfAyahs: 29,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[80],
    juzNumber: 30,
    revelationOrder: 7
  },
  {
    id: 82,
    number: 82,
    name: "الإنفطار",
    englishName: "Al-Infitar",
    englishNameTranslation: "The Cleaving",
    numberOfAyahs: 19,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[81],
    juzNumber: 30,
    revelationOrder: 82
  },
  {
    id: 83,
    number: 83,
    name: "المطففين",
    englishName: "Al-Mutaffifin",
    englishNameTranslation: "The Defrauding",
    numberOfAyahs: 36,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[82],
    juzNumber: 30,
    revelationOrder: 86
  },
  {
    id: 84,
    number: 84,
    name: "الإنشقاق",
    englishName: "Al-Inshiqaq",
    englishNameTranslation: "The Sundering",
    numberOfAyahs: 25,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[83],
    juzNumber: 30,
    revelationOrder: 83
  },
  {
    id: 85,
    number: 85,
    name: "البروج",
    englishName: "Al-Buruj",
    englishNameTranslation: "The Mansions of the Stars",
    numberOfAyahs: 22,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[84],
    juzNumber: 30,
    revelationOrder: 27
  },
  {
    id: 86,
    number: 86,
    name: "الطارق",
    englishName: "At-Tariq",
    englishNameTranslation: "The Nightcomer",
    numberOfAyahs: 17,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[85],
    juzNumber: 30,
    revelationOrder: 36
  },
  {
    id: 87,
    number: 87,
    name: "الأعلى",
    englishName: "Al-A'la",
    englishNameTranslation: "The Most High",
    numberOfAyahs: 19,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[86],
    juzNumber: 30,
    revelationOrder: 8
  },
  {
    id: 88,
    number: 88,
    name: "الغاشية",
    englishName: "Al-Ghashiya",
    englishNameTranslation: "The Overwhelming",
    numberOfAyahs: 26,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[87],
    juzNumber: 30,
    revelationOrder: 68
  },
  {
    id: 89,
    number: 89,
    name: "الفجر",
    englishName: "Al-Fajr",
    englishNameTranslation: "The Dawn",
    numberOfAyahs: 30,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[88],
    juzNumber: 30,
    revelationOrder: 10
  },
  {
    id: 90,
    number: 90,
    name: "البلد",
    englishName: "Al-Balad",
    englishNameTranslation: "The City",
    numberOfAyahs: 20,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[89],
    juzNumber: 30,
    revelationOrder: 35
  },
  {
    id: 91,
    number: 91,
    name: "الشمس",
    englishName: "Ash-Shams",
    englishNameTranslation: "The Sun",
    numberOfAyahs: 15,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[90],
    juzNumber: 30,
    revelationOrder: 26
  },
  {
    id: 92,
    number: 92,
    name: "الليل",
    englishName: "Al-Layl",
    englishNameTranslation: "The Night",
    numberOfAyahs: 21,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[91],
    juzNumber: 30,
    revelationOrder: 9
  },
  {
    id: 93,
    number: 93,
    name: "الضحى",
    englishName: "Ad-Duhaa",
    englishNameTranslation: "The Morning Hours",
    numberOfAyahs: 11,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[92],
    juzNumber: 30,
    revelationOrder: 11
  },
  {
    id: 94,
    number: 94,
    name: "الشرح",
    englishName: "Ash-Sharh",
    englishNameTranslation: "The Relief",
    numberOfAyahs: 8,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[93],
    juzNumber: 30,
    revelationOrder: 12
  },
  {
    id: 95,
    number: 95,
    name: "التين",
    englishName: "At-Tin",
    englishNameTranslation: "The Fig",
    numberOfAyahs: 8,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[94],
    juzNumber: 30,
    revelationOrder: 28
  },
  {
    id: 96,
    number: 96,
    name: "العلق",
    englishName: "Al-Alaq",
    englishNameTranslation: "The Clot",
    numberOfAyahs: 19,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[95],
    juzNumber: 30,
    revelationOrder: 1
  },
  {
    id: 97,
    number: 97,
    name: "القدر",
    englishName: "Al-Qadr",
    englishNameTranslation: "The Power",
    numberOfAyahs: 5,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[96],
    juzNumber: 30,
    revelationOrder: 25
  },
  {
    id: 98,
    number: 98,
    name: "البينة",
    englishName: "Al-Bayyina",
    englishNameTranslation: "The Clear Proof",
    numberOfAyahs: 8,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[97],
    juzNumber: 30,
    revelationOrder: 100
  },
  {
    id: 99,
    number: 99,
    name: "الزلزلة",
    englishName: "Az-Zalzala",
    englishNameTranslation: "The Earthquake",
    numberOfAyahs: 8,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[98],
    juzNumber: 30,
    revelationOrder: 93
  },
  {
    id: 100,
    number: 100,
    name: "العاديات",
    englishName: "Al-Adiyat",
    englishNameTranslation: "The Courser",
    numberOfAyahs: 11,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[99],
    juzNumber: 30,
    revelationOrder: 14
  },
  {
    id: 101,
    number: 101,
    name: "القارعة",
    englishName: "Al-Qari'a",
    englishNameTranslation: "The Calamity",
    numberOfAyahs: 11,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[100],
    juzNumber: 30,
    revelationOrder: 30
  },
  {
    id: 102,
    number: 102,
    name: "التكاثر",
    englishName: "At-Takathur",
    englishNameTranslation: "The Rivalry in world increase",
    numberOfAyahs: 8,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[101],
    juzNumber: 30,
    revelationOrder: 16
  },
  {
    id: 103,
    number: 103,
    name: "العصر",
    englishName: "Al-Asr",
    englishNameTranslation: "The Declining Day",
    numberOfAyahs: 3,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[102],
    juzNumber: 30,
    revelationOrder: 13
  },
  {
    id: 104,
    number: 104,
    name: "الهمزة",
    englishName: "Al-Humaza",
    englishNameTranslation: "The Traducer",
    numberOfAyahs: 9,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[103],
    juzNumber: 30,
    revelationOrder: 32
  },
  {
    id: 105,
    number: 105,
    name: "الفيل",
    englishName: "Al-Fil",
    englishNameTranslation: "The Elephant",
    numberOfAyahs: 5,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[104],
    juzNumber: 30,
    revelationOrder: 19
  },
  {
    id: 106,
    number: 106,
    name: "قريش",
    englishName: "Quraysh",
    englishNameTranslation: "Quraysh",
    numberOfAyahs: 4,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[105],
    juzNumber: 30,
    revelationOrder: 29
  },
  {
    id: 107,
    number: 107,
    name: "الماعون",
    englishName: "Al-Ma'un",
    englishNameTranslation: "The Small Kindnesses",
    numberOfAyahs: 7,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[106],
    juzNumber: 30,
    revelationOrder: 17
  },
  {
    id: 108,
    number: 108,
    name: "الكوثر",
    englishName: "Al-Kawthar",
    englishNameTranslation: "Abundance",
    numberOfAyahs: 3,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[107],
    juzNumber: 30,
    revelationOrder: 15
  },
  {
    id: 109,
    number: 109,
    name: "الكافرون",
    englishName: "Al-Kafirun",
    englishNameTranslation: "The Disbelievers",
    numberOfAyahs: 6,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[108],
    juzNumber: 30,
    revelationOrder: 18
  },
  {
    id: 110,
    number: 110,
    name: "النصر",
    englishName: "An-Nasr",
    englishNameTranslation: "The Divine Support",
    numberOfAyahs: 3,
    revelationType: "Medinan",
    arabicNumber: arabicNumbers[109],
    juzNumber: 30,
    revelationOrder: 114
  },
  {
    id: 111,
    number: 111,
    name: "المسد",
    englishName: "Al-Masad",
    englishNameTranslation: "The Palm Fiber",
    numberOfAyahs: 5,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[110],
    juzNumber: 30,
    revelationOrder: 6
  },
  {
    id: 112,
    number: 112,
    name: "الإخلاص",
    englishName: "Al-Ikhlas",
    englishNameTranslation: "The Sincerity",
    numberOfAyahs: 4,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[111],
    juzNumber: 30,
    revelationOrder: 22
  },
  {
    id: 113,
    number: 113,
    name: "الفلق",
    englishName: "Al-Falaq",
    englishNameTranslation: "The Daybreak",
    numberOfAyahs: 5,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[112],
    juzNumber: 30,
    revelationOrder: 20
  },
  {
    id: 114,
    number: 114,
    name: "الناس",
    englishName: "An-Nas",
    englishNameTranslation: "Mankind",
    numberOfAyahs: 6,
    revelationType: "Meccan",
    arabicNumber: arabicNumbers[113],
    juzNumber: 30,
    revelationOrder: 21
  }
];
